import { useState, useEffect, type FC } from 'react';
import { Deck, Card } from '../types';
import { BookOpen, AlertCircle, Plus, Trash2, Edit3, ArrowRight, RotateCcw, Zap, Share2, Users, Download, Printer, Flame } from 'lucide-react';
import { isDue, getLocalDateString } from '../utils/sm2';

interface DeckListScreenProps {
  decks: Deck[];
  cards: Card[];
  streakDays: number;
  onSelectDeck: (deckId: string, tab: 'study' | 'review' | 'editor' | 'quiz') => void;
  onCreateDeck: (name: string, description: string) => void;
  onDeleteDeck: (deckId: string) => void;
  onResetToDefaults: () => void;
  onShareDeck: (deckId: string) => void;
  onShareToGroup: (deckId: string) => void;
}

export const DeckListScreen: FC<DeckListScreenProps> = ({
  decks,
  cards,
  streakDays,
  onSelectDeck,
  onCreateDeck,
  onDeleteDeck,
  onResetToDefaults,
  onShareDeck,
  onShareToGroup,
}) => {
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newDeckName, setNewDeckName] = useState('');
  const [newDeckDesc, setNewDeckDesc] = useState('');
  const [errorMsg, setErrorMsg] = useState('');

  const todayStr = getLocalDateString();

  useEffect(() => {
    if ('Notification' in window && Notification.permission === 'default') {
      Notification.requestPermission();
    }
  }, []);

  const sendStudyReminder = () => {
    if ('Notification' in window && Notification.permission === 'granted') {
      const dueCount = decks.reduce((sum, d) => sum + getDeckStats(d.id).due, 0);
      new Notification('Cardify Study Reminder', {
        body: dueCount > 0
          ? `You have ${dueCount} card${dueCount > 1 ? 's' : ''} due for review!`
          : 'All caught up! Add new cards or review ahead.',
        icon: '/logo.png',
      });
    }
  };

  // Helper to compute stats for each deck
  const getDeckStats = (deckId: string) => {
    const deckCards = cards.filter((c) => c.deckId === deckId);
    const dueCount = deckCards.filter((c) => isDue(c.dueDate, todayStr)).length;
    return {
      total: deckCards.length,
      due: dueCount,
    };
  };

  const handleCreate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newDeckName.trim()) {
      setErrorMsg('Deck name is required');
      return;
    }
    onCreateDeck(newDeckName.trim(), newDeckDesc.trim());
    setNewDeckName('');
    setNewDeckDesc('');
    setErrorMsg('');
    setShowCreateModal(false);
  };

  // Find if any deck has cards due to recommend studying
  const recommendedDeck = decks.find((d) => getDeckStats(d.id).due > 0);

  const handleExportCsv = (deckId: string, deckName: string) => {
    const deckCards = cards.filter((c) => c.deckId === deckId);
    if (deckCards.length === 0) return;
    const header = 'Front,Back,Tag,CardType,Bookmarked';
    const rows = deckCards.map(c => {
      const front = `"${c.front.replace(/"/g, '""')}"`;
      const back = `"${c.back.replace(/"/g, '""')}"`;
      return `${front},${back},${c.tag},${c.cardType},${c.bookmarked ? 'Yes' : 'No'}`;
    });
    const csv = [header, ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${deckName.replace(/[^a-zA-Z0-9]/g, '_')}_cards.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = (deckId: string, deckName: string) => {
    const deckCards = cards.filter((c) => c.deckId === deckId);
    if (deckCards.length === 0) return;
    const cardRows = deckCards.map((c, i) => `
      <div style="page-break-inside:avoid;border:1px solid #ccc;border-radius:8px;padding:12px;margin-bottom:10px;background:#fff;">
        <div style="font-size:11px;color:#888;margin-bottom:4px;">Card ${i + 1} · ${c.tag}${c.bookmarked ? ' · ⭐' : ''}</div>
        <div style="font-size:14px;font-weight:600;margin-bottom:6px;">${c.front}</div>
        <div style="font-size:13px;color:#333;border-top:1px dashed #ddd;padding-top:6px;">${c.back}</div>
      </div>
    `).join('');
    const html = `<html><head><title>${deckName}</title></head><body style="font-family:sans-serif;max-width:800px;margin:0 auto;padding:20px;">
      <h1 style="font-size:18px;margin-bottom:4px;">${deckName}</h1>
      <p style="font-size:12px;color:#888;margin-bottom:20px;">${deckCards.length} cards · Generated by Cardify</p>
      ${cardRows}
    </body></html>`;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Welcome Banner / Overview */}
      <div className="relative overflow-hidden rounded border border-[#2D333B] bg-[#161B22] p-5 md:p-6">
        <div className="max-w-3xl space-y-3">
          <div className="flex items-center space-x-2">
            <span className="px-2 py-0.5 text-[9px] font-mono tracking-widest bg-[#0D1117] text-[#E3B341] rounded border border-[#30363D] uppercase font-bold">
              Sm-2 engine active
            </span>
            <span className="text-[10px] font-mono text-[#8B949E]">Latency: 0ms (local state)</span>
            {streakDays > 0 && (
              <button
                onClick={sendStudyReminder}
                className="inline-flex items-center gap-1 px-2 py-0.5 text-[9px] font-mono font-bold rounded bg-[#E3B341]/10 text-[#E3B341] border border-[#E3B341]/20 hover:bg-[#E3B341]/20 transition-colors cursor-pointer"
                title="Send test notification"
              >
                <Flame size={11} />
                <span>{streakDays} day streak</span>
              </button>
            )}
          </div>
          <h1 className="text-xl font-bold tracking-tight text-white font-mono">
            Flashcard study instrument
          </h1>
          
          <div className="flex flex-wrap gap-2 pt-1">
            {recommendedDeck ? (
              <button
                onClick={() => onSelectDeck(recommendedDeck.id, 'study')}
                className="inline-flex items-center space-x-2 px-3 py-1.5 bg-[#E3B341] hover:bg-[#F0C24F] text-[#0F1115] text-[11px] font-semibold tracking-wider rounded transition-colors cursor-pointer"
              >
                <span>Study recommended deck now</span>
                <ArrowRight size={12} />
              </button>
            ) : decks.length > 0 ? (
              <div className="inline-flex items-center space-x-2 px-3 py-1 bg-[#1F2937]/50 text-[#3FB950] text-[11px] font-mono rounded border border-[#30363D]">
                <span className="w-1.5 h-1.5 rounded-full bg-[#3FB950] animate-pulse"></span>
                <span>All cards up to date</span>
              </div>
            ) : null}

            <button
              onClick={() => setShowCreateModal(true)}
              className="inline-flex items-center space-x-1.5 px-3 py-1.5 bg-[#21262D] hover:bg-[#30363D] text-white text-[11px] font-semibold tracking-wider rounded border border-[#30363D] transition-colors cursor-pointer"
            >
              <Plus size={12} />
              <span>Create deck</span>
            </button>

            <button
              onClick={onResetToDefaults}
              className="inline-flex items-center space-x-1.5 px-3 py-1.5 text-[#8B949E] hover:text-white text-[11px] font-semibold tracking-wider rounded transition-colors cursor-pointer"
              title="Reset all data"
            >
              <RotateCcw size={12} />
              <span>Flush & reset decks</span>
            </button>
          </div>
        </div>
      </div>

      {/* Main Decks Grid */}
      <div className="space-y-3">
        <div className="flex items-center justify-between border-b border-[#2D333B] pb-1.5">
          <h2 className="text-xs font-bold tracking-widest text-[#8B949E] font-mono">
            Subjects & active decks
          </h2>
          <span className="text-[10px] font-mono text-[#8B949E]">
            {decks.length} {decks.length === 1 ? 'deck' : 'decks'} available
          </span>
        </div>

        {decks.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 px-4 border border-dashed border-[#2D333B] rounded bg-[#161B22]/20 space-y-3">
            <BookOpen size={32} className="text-[#8B949E]" />
            <div className="text-center space-y-1">
              <p className="text-white text-xs font-semibold uppercase font-mono">No decks found</p>
              <p className="text-[11px] text-[#8B949E] max-w-sm">
                Create a custom deck or load the pre-populated sample study cards to start reviewing.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
              <button
                onClick={() => setShowCreateModal(true)}
                className="px-3 py-1.5 bg-[#E3B341] hover:bg-[#F0C24F] text-[#0F1115] text-[11px] font-semibold tracking-wider uppercase rounded transition-colors"
              >
                Create New Deck
              </button>
              <button
                onClick={onResetToDefaults}
                className="px-3 py-1.5 bg-[#21262D] hover:bg-[#30363D] text-white text-[11px] font-semibold tracking-wider uppercase rounded border border-[#30363D] transition-colors"
              >
                Load Default Sample Cards
              </button>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {decks.map((deck) => {
              const { total, due } = getDeckStats(deck.id);

              return (
                <div
                  key={deck.id}
                  id={`deck-card-${deck.id}`}
                  className={`group relative flex flex-col justify-between rounded border p-4 transition-all duration-150 bg-[#161B22] ${
                    due > 0
                      ? 'border-[#E3B341]/40 hover:border-[#E3B341]'
                      : 'border-[#2D333B] hover:border-[#30363D]'
                  }`}
                >
                  <div className="space-y-2">
                    {/* Header */}
                    <div className="flex items-start justify-between">
                      <div className="flex items-center space-x-1.5">
                        <span className={`w-1.5 h-1.5 rounded-full ${due > 0 ? 'bg-[#E3B341]' : 'bg-[#8B949E]'}`}></span>
                        <span className="text-[9px] font-mono text-[#8B949E]">
                          {deck.id.toUpperCase()}
                        </span>
                      </div>

                      {/* Due Count Badge */}
                      {due > 0 ? (
                        <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-mono font-bold bg-[#E3B341]/10 text-[#E3B341] border border-[#E3B341]/20">
                          {due} due now
                        </span>
                      ) : (
                        <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-mono font-bold bg-[#3FB950]/10 text-[#3FB950] border border-[#3FB950]/20">
                          Up to date
                        </span>
                      )}
                    </div>

                    {/* Title & Description */}
                    <div className="space-y-1">
                      <h3 className="text-sm font-bold text-white group-hover:text-[#E3B341] transition-colors font-mono">
                        {deck.name}
                      </h3>
                      <p className="text-[11px] text-[#8B949E] leading-relaxed line-clamp-2">
                        {deck.description || 'No description provided.'}
                      </p>
                    </div>
                  </div>

                  {/* Footer Stats & Actions */}
                  <div className="mt-4 pt-3 border-t border-[#2D333B] flex flex-wrap items-center justify-between gap-2">
                    <div className="text-[9px] sm:text-[10px] text-[#8B949E] font-mono">
                      Total: <span className="text-white font-bold">{total} cards</span>
                    </div>

                    <div className="flex items-center gap-1.5 sm:gap-2 flex-wrap">
                      {/* Manage (Card Editor) */}
                      <button
                        onClick={() => onSelectDeck(deck.id, 'editor')}
                        className="flex items-center justify-center min-w-[44px] min-h-[44px] rounded text-[#8B949E] hover:text-white hover:bg-[#30363D] transition-colors cursor-pointer"
                        title="Manage and edit cards"
                      >
                        <Edit3 size={14} />
                      </button>

                      {/* Quiz */}
                      <button
                        onClick={() => onSelectDeck(deck.id, 'quiz')}
                        className="flex items-center justify-center min-w-[44px] min-h-[44px] rounded text-[#8B949E] hover:text-[#E3B341] hover:bg-[#E3B341]/10 transition-colors cursor-pointer"
                        title="Quiz mode"
                      >
                        <Zap size={14} />
                      </button>

                      {/* Delete */}
                      <button
                        onClick={() => {
                          if (confirm(`Are you sure you want to delete "${deck.name}" and all of its cards?`)) {
                            onDeleteDeck(deck.id);
                          }
                        }}
                        className="flex items-center justify-center min-w-[44px] min-h-[44px] rounded text-[#8B949E] hover:text-[#F85149] hover:bg-[#F85149]/10 transition-colors cursor-pointer"
                        title="Delete deck"
                      >
                        <Trash2 size={14} />
                      </button>

                      {/* Share */}
                      <button
                        onClick={() => onShareDeck(deck.id)}
                        className="flex items-center justify-center min-w-[44px] min-h-[44px] rounded text-[#8B949E] hover:text-[#58A6FF] hover:bg-[#58A6FF]/10 transition-colors cursor-pointer"
                        title="Share deck link"
                      >
                        <Share2 size={14} />
                      </button>

                      {/* Share to Group */}
                      <button
                        onClick={() => onShareToGroup(deck.id)}
                        className="flex items-center justify-center min-w-[44px] min-h-[44px] rounded text-[#8B949E] hover:text-[#58A6FF] hover:bg-[#58A6FF]/10 transition-colors cursor-pointer"
                        title="Share to study group"
                      >
                        <Users size={14} />
                      </button>

                      {/* Export CSV */}
                      <button
                        onClick={() => handleExportCsv(deck.id, deck.name)}
                        className="flex items-center justify-center min-w-[44px] min-h-[44px] rounded text-[#8B949E] hover:text-[#3FB950] hover:bg-[#3FB950]/10 transition-colors cursor-pointer"
                        title="Export as CSV"
                      >
                        <Download size={14} />
                      </button>

                      {/* Export PDF (Print) */}
                      <button
                        onClick={() => handleExportPdf(deck.id, deck.name)}
                        className="flex items-center justify-center min-w-[44px] min-h-[44px] rounded text-[#8B949E] hover:text-[#58A6FF] hover:bg-[#58A6FF]/10 transition-colors cursor-pointer"
                        title="Print as study sheet"
                      >
                        <Printer size={14} />
                      </button>

                      {/* Main Study CTA */}
                      <button
                        onClick={() => onSelectDeck(deck.id, due > 0 ? 'study' : 'editor')}
                        className={`inline-flex items-center space-x-1.5 px-3 h-[44px] rounded text-[10px] font-bold tracking-wider transition-colors cursor-pointer ${
                          due > 0
                            ? 'bg-[#E3B341] text-[#0F1115] hover:bg-[#F0C24F]'
                            : 'bg-[#21262D] text-white hover:bg-[#30363D] border border-[#30363D]'
                        }`}
                      >
                        <span>{due > 0 ? 'Study' : 'Manage'}</span>
                        <ArrowRight size={10} />
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Modal Form for Creating a Deck */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-xs animate-fade-in">
          <div className="w-full max-w-md rounded border border-[#2D333B] bg-[#161B22] p-5 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-[#2D333B] pb-2">
              <h3 className="text-xs font-bold text-[#8B949E] font-mono uppercase tracking-wider">
                Create New Study Deck
              </h3>
              <button
                onClick={() => {
                  setShowCreateModal(false);
                  setErrorMsg('');
                }}
                className="text-[#8B949E] hover:text-white text-[10px] font-mono p-1 hover:bg-[#21262D] rounded"
              >
                CLOSE
              </button>
            </div>

            <form onSubmit={handleCreate} className="space-y-4">
              <div className="space-y-1.5">
                <label className="text-[10px] font-mono tracking-wider text-[#8B949E] uppercase font-bold">
                  Deck Name *
                </label>
                <input
                  type="text"
                  placeholder="e.g., OSPF Protocols & Subnetting Labs"
                  value={newDeckName}
                  onChange={(e) => setNewDeckName(e.target.value)}
                  className="w-full px-3 py-1.5 rounded border border-[#30363D] bg-[#0D1117] text-[#E0E0E0] text-xs font-mono focus:outline-none focus:border-[#E3B341] placeholder-slate-600"
                  maxLength={50}
                  autoFocus
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-mono tracking-wider text-[#8B949E] uppercase font-bold">
                  Description
                </label>
                <textarea
                  placeholder="Summarize the core topics in this deck..."
                  value={newDeckDesc}
                  onChange={(e) => setNewDeckDesc(e.target.value)}
                  className="w-full h-20 px-3 py-1.5 rounded border border-[#30363D] bg-[#0D1117] text-[#E0E0E0] text-xs font-mono focus:outline-none focus:border-[#E3B341] placeholder-slate-600 resize-none"
                  maxLength={160}
                />
              </div>

              {errorMsg && (
                <div className="flex items-center space-x-1.5 text-[#F85149] text-xs bg-[#F85149]/10 p-2 rounded border border-[#F85149]/20">
                  <AlertCircle size={12} />
                  <span>{errorMsg}</span>
                </div>
              )}

              <div className="flex justify-end space-x-2 pt-2">
                <button
                  type="button"
                  onClick={() => {
                    setShowCreateModal(false);
                    setErrorMsg('');
                  }}
                  className="px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-[#8B949E] hover:text-white rounded hover:bg-[#21262D] transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-3 py-1.5 text-xs font-bold uppercase tracking-wider bg-[#E3B341] text-[#0F1115] hover:bg-[#F0C24F] rounded transition-colors cursor-pointer"
                >
                  Create Deck
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
